### ISSUE TITLE
computed state confuse

### ISSUE THREAD

**Issue by ltinyho** [vuex-orm/vuex-orm#170] opened 2018-06-14 06:57 UTC
I can't understand why can get array relation in Vuex state, but array relation is empty in component getters.

vuex state
```
state.quests.data[1726].answers=[2569,6656]
```
component getters
```
quests[0].answers  is empty

```

`image 1`
![image](https://user-images.githubusercontent.com/28479270/41395980-29a58b3c-6fe2-11e8-933a-e6e8cc758ef3.png)

`image 2`
![image](https://user-images.githubusercontent.com/28479270/41395989-2cacb918-6fe2-11e8-999a-592a65d1fee7.png)

**Comment by kiaking** [comment] 2018-06-14 23:59
Hi! Sorry, I'm not sure what your question is... Is everything working fine but you just want to know why the relationship can be resolved by having an empty array?

If that is the question, then the answer is because Vuex ORM is not using that array (`answers`) value when resolving the relations via getters. It looks up for the foreign key defined at model schema definition.

Would this answer make sense to you? 😃

**Comment by timoschwarzer** [comment] 2018-06-18 12:36
It's probably because you use a query and don't request resolving the relationships with the `.with(...)` method. You'd have to do something like this:
```
Quest.query().where('id', Number(1234)).with('answers').first()
```

**Comment by kiaking** [comment] 2018-06-19 00:56
Ah wait also I think you need to change model definition as following I think.

```js
class Quest extends Model {
  static entity = 'quests'

  static fields () {
    return {
      id: this.attr(null),
      answers: this.hasManyBy(Option, 'answers')
    }
  }
}

class Option extends Model {
  static entity = 'options'

  static fields () {
    return {
      id: this.attr(null),
      qid: this.attr(null),
      quest: this.belongsTo(Quest, 'qid')
    }
  }
}
```

**Comment by ltinyho** [comment] 2018-06-20 14:18
@kiaking it is not work, the `options qid` is null. Thank you for your answer.

**Comment by kiaking** [comment] 2018-06-21 01:15
@ltinyho Hmm... Is't possible for you to create some reproducible example or fiddle for this issue? Not sure what is happening here :/

**Comment by kiaking** [comment] 2018-07-05 00:02
@ltinyho Hi! I'll be closing this issue due to inactivity. Please feel free to reopen this issue if you can provide some more information! Hope it solved for you.

**Closed by kiaking** 2018-07-05 00:02 UTC
