### ISSUE TITLE
Deleting or Updating without knowing the id?

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#78] opened 2018-02-14 12:05 UTC
I have a variable containing a record. This records `id` field is `null` because it was newly created and the client can't know the id which will the server assign.

Now I want to update or delete this record. Who can I achieve that?

**Comment by kiaking** [comment] 2018-02-14 15:21
Yea, this can be difficult in such situation. As a best practice, you want to always assign primary key no matter what. You could use `this.increment()` attribute to automatically generate one.

Then, from Vuex ORM 0.18.0, you can get newly created object via return value of the action, you can determine which id to pass to delete method.

```js
// Create new object without id.
const user = await store.dispatch('entities/users/create', { data: ... })

// Delete the newly created user.
store.dispatch('entities/users/delete', user.id)
```

Even if you use `this.increment()` as an attribute, if you pass id explicitly, Vuex ORM will assign the passed value as id.

**Comment by phortx** [comment] 2018-02-14 15:37
Sounds good, I will take this way for the apollo plugin! Thanks :)

**Comment by kiaking** [comment] 2018-02-14 15:40
🚀 👍

**Comment by phortx** [comment] 2018-02-15 12:45
Will this also work for pivot models where the primary key consists of the two foreign keys? 🤔

**Comment by phortx** [comment] 2018-02-15 14:03
If using this method now for delete/updating outdated records. But there is a reactivity issue.

The process ist:

- create a new record via `const user = User.create({ ... })`
- id is generated automatically, let's say its `42`
- call `user.persist()`
- the record is serialized and saved to the server
- the server returns a new record with the real ID, let's say it's `1337`
- the store is updated via `dispatch('update', { where: 42, newRecordFromTheServer })`

Question: What is `user.id` after that?

In my opinion it should be `1337` due to the fact that `user` should contain a reference to the record.

In code this looks like this:

```javascript
 this.user = await User.create({
    name: "Foo Bar",
    email: "foo@bar.net"
});

console.log('ID before', this.user.id); // = 42, correct
await this.user.persist();
console.log('ID after', this.user.id); // = 42, wrong
```

Any idea?

**Comment by iNaD** [comment] 2018-02-16 23:34
So I looked into what is stored when no id is given and what is available via public API.

Using this testcase:

```js
it('can create data by action without id', async () => {
  class User extends Model {
    static entity = 'users'

    static fields () {
      return {
        id: this.attr(null),
        name: this.attr('')
      }
    }
  }

  const store = createStore([{ model: User }])

  const data = {
    name: 'John Doe'
  }

  const createdUser = await store.dispatch('entities/users/create', { data })

  console.log(createdUser);
  /*
  Output:
  User { id: null, name: 'John Doe' }
  */
  console.log(store.state.entities.users.data['_no_key_0'])
  /*
  Output:
  { '$id': [Getter/Setter],
  id: [Getter/Setter],
  name: [Getter/Setter] }
  */
  console.log(store.state.entities.users.data['_no_key_0'].id)
  /*
  Output:
  null
  */
  console.log(store.state.entities.users.data['_no_key_0'].$id)
  /*
  Output:
  undefined
  */
  expect(store.state.entities.users.data['_no_key_0'].name).toBe('John Doe')
})
```

As you can see the record is created as `_no_key_0` (generated by ``return id !== undefined ? id : `_no_key_${this.count++}` `` in `idAttribute` from [Schema.ts:129](https://github.com/vuex-orm/vuex-orm/blob/v0.19.0/src/Schema.ts#L129)), id is `null` as expected, but `$id` shouldn't be `undefined`. This seems to be defined indirectly in `processStrategy` ([Schema.ts:138](https://github.com/vuex-orm/vuex-orm/blob/v0.19.0/src/Schema.ts#L138)) and is based on the model's primary key (which is `null` as we know). So there are two different strategies as it seems? Shouldn't the `id` method in [Model.ts:178](https://github.com/vuex-orm/vuex-orm/blob/v0.19.0/src/Model.ts#L178) return `$id` (if set) or `_no_key_${count}`  if the primaryKey is `null`?

This seems the cause of some problems related to working with id-less records. Also this would enable to receive a usable id via `createUser.$id()` which also currently returns `null`.

**Comment by kiaking** [comment] 2018-02-17 07:56
Hm, yeah @iNaD is correct with the behavior, but the thing is id-less records must be avoided at first place. `_no_key` thing is used mainly with conjunction with `this.increment` attribute, so that after normalizing data, Vuex ORM updates those `_no_key` records with incremented id. If users are not using `this.increment` attribute, they should always provide id value. 

However, it always good to have fail safe so fixing `processStrategy` sounds good idea to me.


@phortx 
To get reactivity, you must use computed property in the Vue Component. With your first example, the user object wouldn't change if you update sate because it's not referenced through computed property. The second example works because you 're reassigning the variable. However, I think there's no issue with second example though : )

**Comment by phortx** [comment] 2018-02-17 08:01
@kiaking alright, thx :)

**Comment by iNaD** [comment] 2018-02-17 08:15
In general if you really need IDs before sending data to a server you should consider using UUIDs or similar conflict save primary keys. Then the server would return the same id and you can easily update the local records from the response. 

This makes your life a lot easier (if it is an option).

**Comment by phortx** [comment] 2018-02-19 08:26
I'm developing the vuex-orm-apollo plugin and I don't want to force the developer into any ID format.

I'm going the way with increment and we'll see if this leads to any issues.

Thanks!

**Comment by kiaking** [comment] 2018-02-19 12:17
Great you found a hint for your way. 

I kinda thought it might be nice for Vuex ORM to have something like `replace` action that replaces existing data with a different ID.

```js
// When having this kind of state.
{
  users: {
    data: {
      '1': { id: 1, name: 'John Doe' },
      '2': { id: 2, name: 'Jane Doe' }
    }
  }
}

// And replace some data.
store.dispatch('entities/users/replace', {
  where: 1,
  data: { id: 3, name: 'John Doe' }
})

// Then state becomes like this.
{
  users: {
    data: {
      '3': { id: 3, name: 'John Doe' }, // <- Replaced!
      '2': { id: 2, name: 'Jane Doe' }
    }
  }
}
```

Maybe you could use this method to replace existing record with new one fetched from the server. What do you think?

**Comment by kiaking** [comment] 2018-02-20 16:52
Similar issue has opened (#90) and it is more focused on that thread so lets bring this discussion over there. Would be really nice if I can get some ideas!

**Closed by kiaking** 2018-02-20 16:52 UTC
