### ISSUE TITLE
$update function does not work with composite primaryKey

### ISSUE THREAD

**Issue by lucasbiguet** [vuex-orm/vuex-orm#455] opened 2019-09-19 13:24 UTC
Calling $update on an object with a composite primary key triggers an error in console:

> You can't specify `where` value as `string` or `number` when you
> have a composite key defined in your model. Please include composite
> keys to the `data` fields.

See this code sandbox that reproduces the problem:

[![Edit vuex-orm relation sample](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vuex-orm-relation-sample-ipnxx?fontsize=14)

**Comment by lucasbiguet** [comment] 2019-09-20 08:17
The error is thrown by [this code](https://github.com/vuex-orm/vuex-orm/blob/master/src/query/Query.ts#L880) because it assumes that if the primary key is composite and the condition is a string it can't find the record. But in that case the `updateById` function works just fine since the condition is equal to $id

I made a quickfix [here](https://github.com/lucasbiguet/vuex-orm/commit/5f117ba24db7ae40f291fd81db66ffbecd3debb7) by just allowing update by string even if the primary key is composite but I'm not sure that it's the best approach; This function may need some more refactoring

**Comment by kiaking** [comment] 2019-09-24 03:24
@lucasbiguet Hi! Thank you so much for the report! Yeah, this is problematic. Please wait a bit for the fix. We're currently working on #261, and it might affect this one as well.

**Comment by SolStis86** [comment] 2020-02-28 12:02
@kiaking is this being released?

**Comment by kiaking** [comment] 2020-03-03 10:25
@SolStis86 Oh yes, it should be fixed I think. So you still see the issue?

**Comment by kiaking** [comment] 2020-03-10 08:05
@SolStis86 Do you have any updates on this?

**Comment by cuebit** [comment] 2020-03-11 03:21
@kiaking sadly, no, this bug is still present.

The issue is that `$update` does not support composite keys per-se. It passes the index as a condition, in the case of composite keys this will be a string, Query throws since it doesn't allow `string` or `number` on models with composite keys.

A patch has been applied to an existing PR (#590) since it bodes well with the composite key work in that branch.

**Comment by kiaking** [comment] 2020-03-11 12:23
Oh, OK. Cool! I'll look into the PR 👍

**Comment by kiaking** [comment] 2020-03-12 13:31
This is fixed by Vuex ORM 0.36.3 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.3

**Closed by kiaking** 2020-03-12 13:31 UTC
Labels: bug, released
