### ISSUE TITLE
hasMany gives null array

### ISSUE THREAD

**Issue by kevadiya93** [vuex-orm/vuex-orm#356] opened 2019-05-03 13:03 UTC
Hi,

For nested data with array of object

```js
{
  "phones": [
    {
      "number": "12345678",
      "verified": true
    },
    {
      "number": "123456789",
      "verified": true
    }
  ],
  "emails": [
     {
       "address": "test@test.com",
       "verified": true
     }
  ]
}
```

In model field declare with hasMany(....)
but it gives null array

Can you suggest me proper field declaration for array of object?

**Comment by kiaking** [comment] 2019-05-08 09:22
@kevadiya93 Hi! Thank you for the feedback. Are you trying to save array of data which is not relational data...? Then you could just use `this.attr()` to store anything.

```js
// I'm assuming that the data is of user object.

class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.attr(null),
      phones: this.attr([]),
      emails: this.attr([])
    }
  }
}
```

**Comment by kiaking** [comment] 2019-05-13 09:15
@kevadiya93 Oh that error is coming from some where outside Vuex ORM. The library wouldn't throw such error. Could you provide me your Model definition and how you're inserting data?

**Comment by kiaking** [comment] 2019-05-23 09:06
@kevadiya93 Just checking in. Did you had any progress on this?

**Comment by emahuni** [comment] 2019-05-27 06:25
I actually think it's a bug in Vuex ORM and using belongsTo is circumventing the issue (was referring to the closed issue #378, now transferring it to here since it seems to be the same thing and is still open). I did the same thing; followed the tutes, and banged my head on the wall several times over a Sails to Vuex ORM model transform package. I  even contributed something with a PR in the documentation section. However, I am still yet to use Vuex ORM without issues. I then thought maybe my code is bad somewhere let me try the example code. So I cloned and ran it. The Todo app seems to work when you run and add a few tasks: 

![Screenshot 2019-05-27 at 07 41 47](https://user-images.githubusercontent.com/7290508/58397876-1f765380-8053-11e9-9fed-9f30ff43170f.png)

But my reason was inherent bug hunting, and closer inspection in Vue-DevTools reveals this issue as in my own apps:

![Screenshot 2019-05-27 at 08 08 13](https://user-images.githubusercontent.com/7290508/58398864-a5e06480-8056-11e9-9f0d-9ef38f9431f9.png)

Notice the other pre-inserted tasks' assignees have assignee ids, but the ones I inserted are null. Consequently the users don't have todos, even for the pre-inserted data. This is the bug!

It happens as you insert data as an object that has an association in it.
This issue is a huge deal breaker!

**Comment by emahuni** [comment] 2019-05-27 08:40
See my other issue post #379 for ideal model definition, if you don't get it then read the Sails models concept, it's really simple to understand 5mins read.

**Comment by kiaking** [comment] 2019-05-30 14:54
@emahuni I've checked issue #379 and I've made comment about model definition. But I would like to check in the `assignee` having value and sometime `null` problem here. Yes it does seem wrong, if the assignee field is a relationship, it should always be null. Is't possible for you to provide me reproducible code?

**Comment by emahuni** [comment] 2019-05-31 08:35
I think we could use the [Todo app example](https://github.com/vuex-orm/vuex-orm-examples), the bug is happening there as well. The result of which is the screenshots above. I am sure it is just one bug affecting hasMany when inserting/creating models. I noticed this:
```js
// Todos.vue
  methods: {
    add () {
      this.$store.dispatch('entities/todos/insert', {
        data: { title: '' }
      })
    }
  }
```
...is being used to insert the todo that's yielding a null in the associations. Whereas this:
```js
// App.vue
  created () {
    // Here we are stubbing the initial data. In the real world, this
    // should be the response from the API Backend.
    const initialData = data

    this.$store.dispatch('entities/todos/create', { data: initialData })
  },
```
is working perfectly as expected, though there are differences. The differences between the two is: `insert` <-> `create` and the other difference is an array is supplied to the App.vue code whereas an object is supplied to the Todos.vue code (I strongly think this is the issue Array vs Object).

**Comment by emahuni** [comment] 2019-05-31 11:34
There is something that you need to be aware of that came to mind. Typescript is not perfect when transpiling to js code. That's why I actually don't use it. It causes horrible issues that I experienced a while ago. It had something to do with `null` something. I forgot what it was but it could be a compilation issue here. Just thought I should mention it.

**Comment by kiaking** [comment] 2019-05-31 12:09
@emahuni OK I've confirmed the issue with the example repo, and found out that the Vuex ORM version was pretty old. I've updated the Vuex ORM and now every `assignee` is becoming `null` as expected. Sorry for the confusion. So at least, having inconsistent foreign key value is not happening on latest version of Vuex ORM I think.

And while this issue is about getting error mentioned by @kevadiya93 which is:

```
{"errors":[{"message":"Field \"phones\" of type \"[Phone!]\" must have a selection of subfields. Did you mean \"phones { ... }\"?","locations":[{"line":14,"column":5}]}]}
```

Not sure what this error is but it's clearly not coming from Vuex ORM. So, let me just close this issue for now. If @kevadiya93 have any progress on the issue, please feel free to reopen it! 🤝

**Closed by kiaking** 2019-05-31 12:09 UTC
Labels: question

**Comment by emahuni** [comment] 2019-05-31 12:12
yes that issue may not be related to Vuex ORM, but what about the null issue, should we use this instead #378?

**Comment by kiaking** [comment] 2019-05-31 12:15
@emahuni I think yes, we should use #378 maybe, I haven't looked into it just yet. But the `null` issue we had on your screen shot is not happening on latest version. We need to have some kind of reproduction code to tackle further.

**Comment by emahuni** [comment] 2019-06-06 13:21
just wondering, what version is working well? my project is using version 0.31.11.

**Comment by kiaking** [comment] 2019-06-06 13:33
The example is now using 0.31.12. I think it would work as same as 0.31.11 though.
https://github.com/vuex-orm/vuex-orm-examples/blob/master/package.json

But also, to be more clear, it's OK if `assignee` have inconsistent value really. Because Vuex ORM will not use that value to lookup relationship.

And also, the issue is gone for the example project, and not sure for your project... If you can provide me your project the nI can look into it! 😃

**Comment by emahuni** [comment] 2019-06-07 05:34
I don't think this has anything to do with my code specifically. I posted a codesandbox on #378 go to #378  and see what I mean. This time I have used getting started. I just copied the getting started code you provided on the documentation to create a Vue code sandbox and the issue is happening with that simple code as well.

**Comment by kiaking** [comment] 2019-06-07 05:40
@emahuni I've described at #378 too but it's expected behavior. The field should always be null inside store.

**Comment by emahuni** [comment] 2019-06-07 05:41
whaaaaaaaa?

**Comment by JackEdwardLyons** [comment] 2020-03-04 06:38
Any news on this and why it should be null?
