### ISSUE TITLE
Many - Many doesn't work

### ISSUE THREAD

**Issue by huy-tran** [vuex-orm/vuex-orm#159] opened 2018-05-17 13:53 UTC
Hi @kiaking ,

I am encountering the issue `Cannot read property 'hasPivotFields' of undefined` when trying to setup Many - Many relationships.

I am using Laravel as Backend so my data structure is
![2018-05-17_23h48_15](https://user-images.githubusercontent.com/15810919/40181627-e796d388-5a2c-11e8-939c-1da40955d7b4.png)

Member model is:

```js
static fields() {
    return {
      id: this.attr(null),
      books: this.belongsToMany(Book, MemberBook, 'memberId', 'bookId'),
    }
}
```

Book Model:

```js
static fields() {
    return {
      id: this.attr(null),
      members: this.belongsToMany(Member, MemberBook, 'bookId', 'memberId''),
    }
}
```

MemberBookModel

```js
static fields() {
    return {
      memberId: this.attr(null),
      bookId: this.attr(null)
    }
}
```

Thank you in advance!

**Comment by kiaking** [comment] 2018-05-21 02:36
Hi! Thank you for the report! The error sounds like it's not available to find the model. Could you give me the `entity` name for the models? Or maybe you should do this...?

```js
store.dispatch('entities/members/insert', {
  data: json.member
})
```

**Comment by huy-tran** [comment] 2018-05-21 03:50
@kiaking 
Hi mate,

The `entity` names are `member`, `book` and `memberBook` respectively. I don't know if the issue of coming from my `pivot` key?

Is it possible for you to show me the data response structure you used in the example?

Thanks heaps!

**Comment by kiaking** [comment] 2018-05-21 12:28
Hmm... strange. OK, so the following test is passing.

```js
it('can create a data with belongs to many relation', async () => {
  class User extends Model {
    static entity = "users"

    static fields() {
      return {
        id: this.attr(null),
        permissions: this.belongsToMany(Role, RoleUser, 'user_id', 'role_id')
      }
    }
  }

  class Role extends Model {
    static entity = 'roles'

    static fields() {
      return {
        id: this.attr(null)
      }
    }
  }

  class RoleUser extends Model {
    static entity = 'roleUser'

    static primaryKey = ['role_id', 'user_id']

    static fields() {
      return {
        role_id: this.attr(null),
        user_id: this.attr(null)
      }
    }
  }

  const store = createStore([{ model: User }, { model: Role }, { model: RoleUser }])

  await store.dispatch('entities/users/create', {
    data: {
      id: 1,
      permissions: [{ id: 1 }, { id: 2 }]
    }
  })

  const expected = createState('entities', {
    users: {
      '1': { $id: 1, id: 1, permissions: [1, 2] }
    },
    roles: {
      '1': { $id: 1, id: 1 },
      '2': { $id: 2, id: 2 }
    },
    roleUser: {
      '1_1': { $id: '1_1', role_id: 1, user_id: 1 },
      '2_1': { $id: '2_1', role_id: 2, user_id: 1 }
    }
  })

  expect(store.state.entities).toEqual(expected)
})
```

Now, the key name `pivot` will be ignored by Vuex ORM because it doesn't show up on your model definition. But it shouldn't throw any error... It looks like it should work.

Is it possible for you to provide me the full code or create reproducible fiddle? You could send me an email if the code is too private to show to the public! kia.king.08@gmail.com

**Comment by kiaking** [comment] 2018-06-25 03:02
@huy-tran Hi! Do you have any update on this? I'm kinda stack without some reproducible code :/

**Comment by huy-tran** [comment] 2018-06-25 03:56
@kiaking Oh sorry mate, I just forgot this entirely. We can close the issue for now. However, I will send email to you if I can asap. I am currently finalizing some projects. Thanks for your great support again!

Cheers!

**Comment by kiaking** [comment] 2018-06-25 04:00
OK! Thank you for the confirmation! I'll close the issue for now.

Please feel free to reopen this issue if you encounter this again, or open another issue in case you have any other troubles : )

Good luck for your project! 👍

**Closed by kiaking** 2018-06-25 04:00 UTC

**Comment by josh-m-sharpe** [comment] 2019-03-26 10:13
I too had this error: `Cannot read property 'hasPivotFields' of undefined` 

In my case it was caused by attempting to use a model before registering it correctly.  That is, I forgot to include this line: `database.register(AwsSync, aws_sync)`

It might be nice to have a slightly more useful error message in this case?

Cheers

**Comment by kiaking** [comment] 2019-04-15 09:36
@josh-m-sharpe Thank you for the report! Yes, we should have better error messages :/
