### ISSUE TITLE
Limiting the number of entities in a one-to-many relationship

### ISSUE THREAD

**Issue by tweaker** [vuex-orm/vuex-orm#399] opened 2019-07-08 21:25 UTC
How can I get, in a one-to-many relationship, a limited number of entities?

In Laravel I use the code:
```php
$limit = 12;
$persons = Person::get()
    ->map(function (Person $person) use ($limit) {
        return $person->setRelation('media', $person->media()
            ->latest('added_at')
            ->take($limit)
            ->get());
    });
```
In this example, I get only two entities for all parents:

```js
PersonModel.query()
    .with('media', (query => {
        query.limit(2)
    }))
    .get()
```

```json
[
  {
    "id": 1,
    "loading": false,
    "mediaCount": 68,
    "media": []
  },
  {
    "id": 2,
    "loading": false,
    "mediaCount": 11,
    "media": []
  },
  {
    "id": 3,
    "loading": false,
    "mediaCount": 48,
    "media": [
      {
        "id": 6082,
        "personId": 3,
        "desription": ""
      },
      {
        "id": 6083,
        "personId": 3,
        "desription": ""
      }
    ]
  }
]
```

**Comment by kiaking** [comment] 2019-07-09 14:12
@tweaker Hi! Thank you so much for the report! Yeah, Vuex ORM eager load works same as Laravel eager load, so this is by design. You can do something like below I think. Would it make sense to you?

```js
PersonModel.query().with('media').get().map((person) => {
  person.media = person.media.slice(0, 2)

  return person
})
```

**Comment by tweaker** [comment] 2019-07-10 05:19
> @tweaker Hi! Thank you so much for the report! Yeah, Vuex ORM eager load works same as Laravel eager load, so this is by design. You can do something like below I think. Would it make sense to you?
> 
> ```js
> PersonModel.query().with('media').get().map((person) => {
>   person.media = person.media.slice(0, 2)
> 
>   return person
> })
> ```
Thank you very much for your answer! It turned out I need sorting.
It turned out like this:
```js
PersonModel.query()
    .orderBy('updatedAt', 'desc')
    .get()
    .map(function (person) {
        person.media = MediaModel.query()
            .where('personId', person.id)
            .orderBy('addedAt', 'desc')
            .limit(15)
            .get();
        return person
    });
```

**Comment by kiaking** [comment] 2019-07-23 12:37
#399
@tweaker Thank you for trying out! Yeah, that looks good. But in that case, you could first filter Media using eager load constraint. It'll save executing extra query so it might be a bit faster.

```js
PersonModel.query()
    .with('media', function (query) {
        query.orderBy('addedAt', 'desc')
    })
    .orderBy('updatedAt', 'desc')
    .get()
    .map(function (person) {
        person.media = posts.media.slice(0, 15)

        return person
    })
```

I'll be closing this issue for now. Thank you so much for the feedback! 🤝

**Closed by kiaking** 2019-07-23 12:37 UTC
Labels: question
