### ISSUE TITLE
Attribute mutator brakes after upgrading from 0.34.1 to 0.35.1

### ISSUE THREAD

**Issue by szhorvath** [vuex-orm/vuex-orm#547] opened 2020-01-29 10:55 UTC
Hi,
Fantastic package. I love it. Much appreciated.

I have just upgraded to the v0.35.1 and my attribute date mutator broke. 
I use a function as a second argument to parse iso date string.

```javascript
  static fields() {
    return {
      id: this.attr(null),
      customerRef: this.attr(null),
      accountId: this.attr(null),
      invoiceId: this.attr(null),
      parentAccountId: this.attr(null),
      accountName: this.string(""),
      documentStatus: this.string(""),
      documents: this.attr([]),
      revision: this.string(""),
      memo: this.string("N/A"),
      priceExcludeVat: this.number(null),
      currency: this.attr("GBP"),
      vat: this.string(null),
      destination: this.string("").nullable(),
      accountTown: this.attr(null),
      accountAddress: this.attr({}),
      deliveryAddress: this.attr({}),
      createdAt: this.attr(null, this.toDate).nullable(),
      orderDate: this.attr(null, this.toDate).nullable(),
      deliveryDate: this.attr(null, this.toDate).nullable(),
      invoiceDate: this.attr(null, this.toDate).nullable(),
      dueDate: this.attr(null, this.toDate).nullable(),
      items: this.hasMany(OperaOrderItem, "orderId"),
      deliveries: this.hasMany(OperaOrderDelivery, "orderId")
    };
  }

  static toDate(value) {
    return value ? new Date(value) : null;
  }
```

The problem is that the mutator function is executed multiple times and shows 'Invalid Date' but in 0.34.1 that did not cause any problem.

Probably I am using the mutator wrong?

Thanks

**Comment by cuebit** [comment] 2020-02-01 02:44
Duplicate of #524

**Comment by kiaking** [comment] 2020-02-01 15:58
Yeah this is the same cause as #524. You're using the mutator correctly, though we must re-think how mutator gets executed. I'll close this issue but let's continue discussion at #524.

**Closed by kiaking** 2020-02-01 15:58 UTC
