### ISSUE TITLE
Cannot update pivot data

### ISSUE THREAD

**Issue by Marchiuzzz** [vuex-orm/vuex-orm#728] opened 2021-05-17 07:50 UTC
I'm trying to follow the method to update pivot data described in the docs but it just doesn't seem to work.
I have PageSection model
```
import { Model } from '@vuex-orm/core'
import ObjectParameter from './ObjectParameter'
import DynamicAbstractObject from './DynamicAbstractObject'
import PageSectionDynamicAbstractObject from './PageSectionDynamicAbstractObject'
import SectionParam from './SectionParam'

export default class PageSection extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'pageSections'

  // List of all fields (schema) of the post model. `this.attr` is used
  // for the generic field type. The argument is the default value.
  static fields () {
    return {
        id: this.attr(null),
        page_id: this.attr(null),
        section_id: this.attr(null),
        objectParameters: this.hasMany(ObjectParameter, 'page_section_id'),
        sectionObjects: this.belongsToMany(DynamicAbstractObject, PageSectionDynamicAbstractObject, 'page_section_id', 'object_id'),
        param: this.hasOne(SectionParam, 'page_section_id')
    }
  }

  static apiConfig = {
    actions: {
      fetch () {
        return this.get('/api/pagesections', {
            dataKey: 'data'
        });
      }
    }
  }
}
```
**DynamicAbstractObject model**
```
import { Model } from '@vuex-orm/core'
import Tag from './Tag'
import Grade from './Grade'
import Gallery from './Gallery'
import ObjectGallery from './ObjectGallery'
import ObjectTag from './ObjectTag'
import DynamicObject from './DynamicObject'
import ObjectGrade from './ObjectGrade'
import DynamicEntity from './DynamicEntity'
import ObjectEvent from './ObjectEvent'
import DynamicAbstractObjectObjectEvent from './DynamicAbstractObjectObjectEvent'

export default class DynamicAbstractObject extends Model {
    // This is the name used as module name of the Vuex Store.
    static entity = 'dynamicAbstractObjects'

    // List of all fields (schema) of the post model. `this.attr` is used
    // for the generic field type. The argument is the default value.
    static fields () {
        return {
            id: this.attr(null),
            title: this.string(''),  
            faIcon: this.string(''),
            object_id: this.string(''),
            unique_entity_id: this.string(''),
            tags: this.belongsToMany(Tag, ObjectTag, 'abstract_object_id', 'tag_id'),
            media: this.belongsToMany(Gallery, ObjectGallery, 'abstract_object_id', 'gallery_id'),
            fileImage: this.attr({
                url: this.attr(null),
                title: this.attr(null),
                size: this.attr(null),
            }),
            grades: this.belongsToMany(Grade, ObjectGrade, 'abstract_object_id', 'grade_id'),
            object_type: this.belongsTo(DynamicObject, 'object_id'),
            list_type: this.attr({}),
            position: this.attr(1000),
            entity: this.hasOne(DynamicEntity, 'unique_entity_id', 'unique_entity_id'),
            events: this.belongsToMany(ObjectEvent, DynamicAbstractObjectObjectEvent, 'object_id', 'object_event_id'),
        }
    }

    static apiConfig = {
        actions: {
            fetch () {
                return this.get('/api/dynamicobjects', {
                    dataKey: 'data'
                });
            }
        }
    }
}
```
And the intermediate model **PageSectionDynamicAbstractObject**
```
import { Model } from '@vuex-orm/core'


export default class PageSectionDynamicAbstractObject extends Model {
    // This is the name used as module name of the Vuex Store.
    static entity = 'page_section_content'
    // List of all fields (schema) of the post model. `this.attr` is used
    // for the generic field type. The argument is the default value.
    static primaryKey = ['page_section_id', 'object_id']
    static fields () {
        return {
            id: this.attr(null),
            object_id: this.attr(null),
            page_section_id: this.attr(null),
            position: this.attr(1000),
        }
    }

    static apiConfig = {
        actions: {
            fetch () {
                return this.get('/api/page_section_content', {
                    dataKey: 'data'
                });
            }
        }
    }
}
```

Field that interests me is the "position" field on the intermediate table, I need to update it. So here's what I'm trying to do
```
PageSection.update({
                where: this.section.id,
                data: {
                    sectionObjects: withPosition
                },
                create: ['page_section_content']
            });
```
The "withPosition" object contains the following:
```
[
  {
    "$id": "57",
    "id": 57,
    "title": "Kopiark",
    "faIcon": "null",
    "object_id": "1005",
    "unique_entity_id": "1005_4",
    "$isDirty": false,
    "$isNew": false,
    "pivot": {
      "$id": "[23,57]",
      "id": 691,
      "object_id": 57,
      "page_section_id": 23,
      "position": 0,
      "$isDirty": false,
      "$isNew": false
    }
  },
  {
    "$id": "50",
    "id": 50,
    "title": "Footer",
    "faIcon": "",
    "object_id": "1005",
    "unique_entity_id": "1005_3",    
    "$isDirty": false,
    "$isNew": false,
    "pivot": {
      "$id": "[23,50]",
      "id": 690,
      "object_id": 50,
      "page_section_id": 23,
      "position": 1,
      "$isDirty": false,
      "$isNew": false
    }
  }
]
```
As you can see, I'm including the "pivot" data as described in docs but the thing is, when this is retrieved, pivot isn't appearing as changed and I don't know where to look for an issue, am I updating it wrongly somehow or is it a problem with retrieving?
This is how I retrieve data:
```
computed: {
        items(){
            var section = PageSection.query().withAllRecursive(5).where('id', this.section.id).first();
            var objects = section.sectionObjects;
            if(!objects){
                return [];
            }
            objects = objects.sort((a,b) => (a.pivot.position > b.pivot.position) ? 1 : ((b.pivot.position > a.pivot.position) ? -1 : 0));
            return objects;
        }
    },
```

**Comment by musixite** [comment] 2021-05-17 22:32
I ran pretty much in the same issue.
it seems the pivot is not reliable so I used the pivot table directly and then it works
something like this ->

```
galleryImage() {
      const query = ResourcesGalleryImage.query()
        .where("gallery_id", Number(this.galleryId))
        .get()
        .map(({ position, image_id }) => ({
          image_id,
          position,
        }));
      return query;
    },
```

**Comment by cuebit** [comment] 2021-05-18 00:18
There is a known issue regarding pivot data in m:m relation types. What @musixite suggested may work for you.

P.S. What is this? Never seen this before 👀 

```js
fileImage: this.attr({
    url: this.attr(null),
    title: this.attr(null),
    size: this.attr(null),
}),
```

Closing this since it's a duplicate of #602 amongst a few others.

**Closed by cuebit** 2021-05-18 00:18 UTC

**Comment by Marchiuzzz** [comment] 2021-05-18 06:19
> I ran pretty much in the same issue.
> it seems the pivot is not reliable so I used the pivot table directly and then it works
> something like this ->
> 
> ```
> galleryImage() {
>       const query = ResourcesGalleryImage.query()
>         .where("gallery_id", Number(this.galleryId))
>         .get()
>         .map(({ position, image_id }) => ({
>           image_id,
>           position,
>         }));
>       return query;
>     },
> ```

Yup, working directly with the pivot table did the trick.

@cuebit Well my object may or may not have fileImage property, which is actually an object. Since I couldn't find any info on conditional relationships, I've defined this field as an object containing a few properties, so if my api returns this: 
```
[
  {
    ...
    "fileImage": {
      "url" : "some url"
      "title": "some title"
      "size" : "50"
    }
    ...
  }
]
```
I will get and object containing this property.
It's just a workaround I figured, is it a bad practice to do this?

**Comment by cuebit** [comment] 2021-05-18 13:22
@Marchiuzzz you only need `fileImage: this.attr({})` since nested properties are not handled by Vuex ORM, they'll simply be populated with whatever nested data you supply to the field i.e. no casting etc. If it works and helps you identify your fields data then cool 😎
