### ISSUE TITLE
0.35.2 vuex-orm.min.js:formatted:3525 Uncaught (in promise) TypeError: Class constructor x cannot be invoked without 'new' 

### ISSUE THREAD

**Issue by kamwing** [vuex-orm/vuex-orm#578] opened 2020-02-26 07:26 UTC
```js
An.prototype.createBindingModel = function(t) {
        var e, n = this, r = (ft(i, e = t),
        i.store = function() {
            return n.store
        }
        ,
        i);
        function i() {
            return null !== e && e.apply(this, arguments) || this
        }
        return Object.defineProperty(r, "name", {
            get: function() {
                return t.name
            }
        }),
        r
    }
```

**Comment by cuebit** [comment] 2020-02-26 07:30
Duplicate of #544

**Closed by cuebit** 2020-02-26 07:30 UTC
Labels: duplicate
