### ISSUE TITLE
Simple code with belongsToMany

### ISSUE THREAD

**Issue by mrFANRA** [vuex-orm/vuex-orm#395] opened 2019-06-29 10:20 UTC
Hello.

Im lost a day in simple issue =(. Can somebody help me please with belongsToMany?
OfferModel has many places. But in the end relation is always empty ...
What is wrong in my code?

```js
export default class OfferModel extends Model{
    static entity = 'offers';

    static fields () {
        return {
            id: this.number(null),
            title: this.string(''),
            places: this.belongsToMany(PlaceModel, OfferPlacePivot,"offer_id","place_id"),
        }
    }
}

export default class PlaceModel extends Model{
    static entity = 'places';

    static fields () {
        return {
            id: this.number(0),
            title_nominative: this.string(''),
        }
    }
}

export default class OfferPlacePivot extends Model{
    static entity = 'offerPlacePivot';

    static primaryKey = ['place_id', 'offer_id'];

    static $fields() {
        return {
            offer_id:this.attr(null),
            place_id:this.attr(null),
        }
    }
}


// =====================
PlaceModel.insert({data:{
		id:1,
		title_nominative:"title_nominative",
	}});

OfferModel.insert({
	data:{
		id:1,
		title:"test offer",
		places:[
			{offer_id:1,place_id:1}
		]
	}
});


console.log(OfferModel.query().withAllRecursive().where("id",1).first().places); // -> empty array =(
```

**Comment by kkyouhei** [comment] 2019-07-05 10:25
@mrFANRA thank you for the report!
I’ll research for the it’s cause.

**Comment by kkyouhei** [comment] 2019-07-06 05:55
Hi @mrFANRA 
please modify $fields method name to fields.

**Comment by mrFANRA** [comment] 2019-07-08 13:54
Hello @kkyouhei . Thanks for reply!

I changed method and update to latest version, but still some response.

**Comment by kiaking** [comment] 2019-07-09 00:02
@mrFANRA Oh, I see the issue here. OK, so you are passing OfferPlacePivot to OfferModel, but OfferModel has relationship to PlaceMode. So, you should be passing PlaceModel directly to the OfferModel.

```js
OfferModel.insert({
  data: {
    id: 1,
    title: "test offer",
    places: [
      { id: 1, title_nominative: "title_nominative" }
    ]
  }
});
```

The above will automatically generate OfferPlacePivot records for you.

Or, if you want to create pivot record explicitly, you could create each separately as well.

```js
PlaceModel.insert({
  data: {
    id: 1,
    title_nominative: "title_nominative",
  }
});

OfferModel.insert({
  data: {
    id: 1,
    title: "test offer"
  }
});

OfferPlacePivot.insert({
  data: {
    offer_id: 1,
    place_id: 1
  }
})
```

**Comment by mrFANRA** [comment] 2019-07-10 08:34
JS make me cry sometimes. Now its works! =)

**Comment by mrFANRA** [comment] 2019-07-10 19:59
Maybe Im wrong, but its looks like belongsToMany relations is empty only in server rendering side. Im using nuxt ...

**Comment by mrFANRA** [comment] 2019-07-11 14:29
@kiaking Can you test this plaese? Im not understand it is bug or my fail. belongsToMany not working in SSR with NuxtJS


```
export default class OfferModel extends Model{
    static entity = 'offers';

    static fields () {
        return {
            id: this.number(null),
            title: this.string(''),
            images: this.belongsToMany(ImageModel,OfferImagePivot,"offer_id","image_id"),
        }
    }
}


export default class ImageModel extends Model {
    static entity = 'images';

    static fields () {
        return {
            id: this.number(0),
            src: this.attr(''),
        }
    }
}

export default class OfferPlacePivot extends Model{
    static entity = 'offerImagePivot';

    static primaryKey = ['image_id', 'offer_id'];

    static fields() {
        return {
            id:this.increment(),
            offer_id:this.attr(null),
            image_id:this.attr(null),
        }
    }
}

// Component:
export default {
        name: "index",
        data() {
            return{
                offer1:false,
                offer2:false,
            }
        },
        asyncData ({ store }) {
            OfferModel.insert({
                data:{
                    id:1,
                    title:"first offer",
                    images:[
                        {id:1, src:"1.jpg"},
                        {id:2, src:"2.jpg"},
                    ],
                }
            });
        },
        created() {
            OfferModel.insert({
                data:{
                    id:2,
                    title:"Second offer",
                    images:[
                        {id:3, src:"3.jpg"},
                        {id:4, src:"4.jpg"},
                    ],
                }
            });

            // Images is empty only on server render side. But if reload script on client side all is fine here =(
            this.offer1 = OfferModel.query().whereId(1).withAllRecursive().first();

            
            // Always has images
            this.offer2 = OfferModel.query().whereId(2).withAllRecursive().first();
        }
    }
```

**Comment by kiaking** [comment] 2019-07-23 12:39
@mrFANRA I'm not 100%  sure, but maybe this is because of asynchronous method execution. `insert` method is calling Vuex Action hence it is async function. So maybe you must wait for it. Could you try adding async and await in `asyncData`?

```js
export default {
    ...

    async asyncData ({ store }) { // <- async.
        await OfferModel.insert({ // <- await
            data:{
                id:1,
                title:"first offer",
                images:[
                    {id:1, src:"1.jpg"},
                    {id:2, src:"2.jpg"},
                ],
            }
        });
    },

    ...
}
```

**Comment by mrFANRA** [comment] 2019-07-23 16:33
@kiaking unfortunately didn't help =(

**Comment by kiaking** [comment] 2019-07-23 23:55
@mrFANRA Damn... This is so wired because I'm doing this all the time (except I'm mostly using `fetch` instead of `asyncData`, but It doesn't matter I guess...?).

Is it possible for you to create a reproducible repo for this one? I need to dig in to find out more.

**Comment by kiaking** [comment] 2019-08-23 02:10
@mrFANRA Hi! Did you make it working?

**Comment by mrFANRA** [comment] 2019-08-23 06:30
Hi! I check this issue few days ago.

I think my mistake was that I did not use computed method for retrived model.

```
computed:{
            offer1:function () {
                return OfferModel.query().whereId(1).withAllRecursive().first();
            },
        },

```

**Comment by kiaking** [comment] 2019-08-26 01:55
@mrFANRA Oh, OK! Great. Thank you for the confirmation, and I'm happy to hear you found the solution.

I'll be closing this issue. Please feel free to open another one if there's anything!

**Closed** 2019-08-26 01:55 UTC
Labels: question
