### ISSUE TITLE
Feature to set and get property data on pivot model.

### ISSUE THREAD

**Issue by Fnxxxxo** [vuex-orm/vuex-orm#682] opened 2020-09-14 07:24 UTC
#### Is your feature request related to a problem? Please describe...

A relation about Employee and Organization many-to-many relationship. It seems not way to set and get isLeader data from the pivot model

#### Describe the solution you'd like

```
Employee.insert({
  data: {
    organizations: [{
      id: 'id',
      pivot: {
        isLeader: true
      }
    }]
  }
})
```
Where get data from the query, the pivot model holds this property data.

#### Describe alternatives you've considered

Currently, I have not walk around.

**Comment by cuebit** [comment] 2020-09-25 23:39
Duplicate of #602

**Closed by cuebit** 2020-09-25 23:39 UTC
Labels: duplicate
