### ISSUE TITLE
Nested relationship creation 

### ISSUE THREAD

**Issue by huy-tran** [vuex-orm/vuex-orm#123] opened 2018-03-19 07:13 UTC
I am working on a project of Laravel + VueJs. I use PHP Fractal to transform my api data to the following structure
```
  member: {
    data: {
      id: 1,
      user_id: 1,
      user: {
        data: {
          id: 1
        }
      }
    }
  }
```

It works perfectly when I create a Member Model by getting the data key on **member** But when I have a look at the relationship (belongsTo between Member - User ) then I got the following schema

```
// Member model
{
  user:"_no_key_1"
}

// User Model
{
  data {
    '_no_key_1': {...}
  }
}
```

Should I reduce the API response first then dispatch the VuexORM create action or is there any way to do that via relationship definition?

For example: `user: this.belongsTo(User, 'user_id', 'user.data')`

Thanks in advanced for any help!

**Comment by kiaking** [comment] 2018-03-19 07:38
I would say reducing the data before hand is better approach since it makes things more clearer. You could define nested fields (Vuex ORM supports this) but I think it'll lead to some unexpected behavior...

```js
class Member extends Model {
  static entity = 'member'

  // You can do this.
  static fields () {
    return {
      id: this.attr(null),
      user_id: this.attr(null),
      user: {
        data: this.belongsTo(User, 'user_id')
      }
    }
  }
}

// But then you have to call getters like this...
const member = store.getters['entities/member/query']().with('data').first()

/*
  {
    id: 1,
    user_id: 1,
    user: {
      data: User { ... }
    }
  }
*/
```

And also it wouldn't work with many relation I guess. So the best solution is to make change on server side to return without `data`. If this is common structure, we could think of handling it at Vuex ORM. Not sure what's the best API for that but...

**Comment by huy-tran** [comment] 2018-03-19 13:27
@kiaking Thanks for your prompt reply. I do love your work on this library.

So the workflow should look like: Fetch API -> restructure data response -> interact with VuexORM.?

Furthermore I have some issues with relationship definition.

```
//Member.js
static fields() {
    return {
      id: this.attr(null),
      userId: this.attr(null),
      user: this.belongsTo(User, 'userId'),
      locations: this.morphMany(Location, 'locatableId', 'locatableType')
    }
  }
```

```
// User.js
  static entity = 'user'

  static fields() {
    return {
      id: this.attr(null),
      member: this.hasOne(Member, 'userId'),
    }
  }
}
```

```
// Location.js
static fields() {
    return {
      id: this.attr(null),
      locatableId: this.attr(null),
      locatableType: this.attr(null),
      locatable: this.morphTo('locatableId', 'locatableType')
    }
  }
```

With these definitions, I am able to do 

```
this.$store.getters['entities/member/query']()
  .with('user')
  .with('locations')
  .find(id)
```

I can see the related *user* and *locations* inside *member*. But trying to do the reverse giving me null. Just wondering if I missed any point?

Thanks heaps again !

**Comment by kiaking** [comment] 2018-03-19 17:15
> So the workflow should look like: Fetch API -> restructure data response -> interact with VuexORM.?

Yes, in your case, unfortunately, that is the path you have to take for now. It kinda sad though, because the one of the biggest power of Vuex ORM is that it does such restructuring for you :/

> I can see the related user and locations inside member. But trying to do the reverse giving me null. Just wondering if I missed any point?

Revers you mean fetching `Member` through `User` right? That's odd because if the Member can retrieve the User, User should also be able to fetch Member. Your model schema looks valid.

Is' possible for you to provide code that can reproduce your issue?

**Comment by cjcrawford** [comment] 2018-04-03 21:43
I had this issue using fractal. I fixed it by providing a default serializer so my nested relations didn't transform into a data object within the related includes.

**Comment by huy-tran** [comment] 2018-04-04 03:48
@kiaking @cjcrawford Hi guys, I had to refactor my Fractal so VuexOrm can work with. I haven't got any issues so far.

@kiaking One issue is sometimes when I update or insert a new record with relationships. When viewing data inside Vue Devtool I can't see the reference key, it's `null`.

However when running a query builder I get the expected result.

Thanks guys !

**Comment by kiaking** [comment] 2018-04-04 13:06
Great! Glad to hear it's working.

> One issue is sometimes when I update or insert a new record with relationships. When viewing data inside Vue Devtool I can't see the reference key, it's null.

This might be expected behavior. If you pass `null` to the primary key, it will use `null` as key. Currently, everything except `undefined` is a valid key value : ) And query builder can get nulls too.

Anyway, I'll close this issue since it seems like solved. Please feel free to open another issue if you have any other troubles! 🍻

**Closed by kiaking** 2018-04-04 13:06 UTC

**Comment by huy-tran** [comment] 2018-11-01 23:46
@malinushj 

Hi mate,

Your API response must match with your VuexORM schema.

I removed the wrapped **data** key in all nested relation. For example:

```js
member: {
  id: 1,
  name: 'ABC',
  locations: [
    {
       id: 1,
       address: 'xyz'
    },
   {
      id: 2,
      address: 'abc'
   }
  ]
}
```

What are you using for BackEnd? I am using Laravel and I had to customise the transformer.

Hope this helps!

**Comment by malinushj** [comment] 2018-11-02 07:20
@kiaking @huy-tran I ended up manually parsing the response into ORM models because for this response:
```js
member: {
  id: 1,
  name: 'ABC',
  location_id: 1,
  location: {
       id: 1,
       address: 'xyz'
    }
}
```
mapped like:
```js
// Member.js
static fields() {
    return {
      id: this.attr(null),
      name: this.attr(''),
      location_id: this.attr(null),
      location: this.belongsTo(Location, 'location_id')
    }
  }
```
I would receive errors from the ORM, thinking it's because `location` is ambiguous for both having the data and relation attached to it? It's weird since I know this works if it was an array with `locations`.
Am I missing something?

**Comment by kiaking** [comment] 2018-11-02 08:32
This is really wired. It should totally work. The `belongsTo` relationship is one to one so the `location` should be an object, not an array. Are you sure you're using the `belongsTo` attribute?

**Comment by malinushj** [comment] 2018-11-02 14:12
@kiaking @huy-tran Ehm, I've had a second look and indeed it works, I have no idea why it didn't work the first time, will remain a mystery 👀 
Thank you guys for your help! Love this package!

**Comment by kiaking** [comment] 2018-11-05 09:30
Great! Good to hear that : )  Please let us know if there's anything.
